[project]
name = "docstream"
version = "0.1.0"
description = "Add a short description here"
authors = ["V <nandithebull@outlook.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
server = {cmd="FLASK_DEBUG=1 flask run --host 0.0.0.0"}

[dependencies]
sqlalchemy = "2.0.23.*"
flask = "3.0.0.*"
flask-cors = "4.0.0.*"
nodejs = ">=20.9.0,<20.10"

[pypi-dependencies]
flask-socketio = "*"


